permalink: /:year/:month/:day/:title.html
paginate: 10
markdown: redcarpet
redcarpet: 
    extensions: ["fenced_code_blocks", "tables", "highlight", "with_toc_data", "strikethrough", "underline"]

# 作者信息
author: 
  name: Xuenan Guo
  email: gxnhit@gmail.com
  link: http://Hitatm.github.io
  weibo: http://weibo.com/xnguo
  github: http://github.com/lay1010
  music: http://site.douban.com/linanya
  linkedin: https://www.linkedin.com/in/ganan

# 站点信息
title: gxnの小站
description: personal blog
url: http://nxg.com
rss_url: /pages/atom.xml

# gavatar头像及Favicon
gavatar: /public/img/sky.jpg
favicon: /public/img/sky.jpg

# google analytics 设置
ga:
  id: UA-54262064-1 
  url: nxg.com

# disqus 设置
disqus:
  shortname: Anan

# 主题设置，自动激活某个标签
active: 技术

# 首页除了最新文章外显示分类
cates: 
  - Optimization
  - LaTeX


gems: [jekyll-paginate]

# 中文本地化
locals:
  tags: 标签
  about: 关于
  newest: 最新文章
  archive: 归档